saltstack-formulas/postfix-formula

postfix/config.sls
postfix/files/main.cf
postfix/files/master.cf
postfix/init.sls

@nmadhok : here you go - this adds SPF support.

add spf handling

---

postfix/map.jinja

Adding RedHat support to formula

add RedHat section to map.jinja

---

pillar.example

Closes https://github.com/saltstack-formulas/postfix-formula/issues/12

reverted commit 6286442 to avoid promoting grain lookup in pillars

---

postfix/files/main.cf
postfix/init.sls

Here is a proposal macro for dealing with files that need to be postmap'ed.
Beware that I have not been able to run it as I do not have a setup needing any of it yet.

#29 postmap macro

---

postfix/init.sls

A stupid overlook on my part when writing `postmap_macro`.

Do not leak passwords

---

postfix/files/main.cf

fix missing bracket

---

README.rst
postfix/map.jinja
postfix/mysql.sls
postfix/pcre.sls

install postfix addons ( Debian Only)

---

postfix/mysql.sls
postfix/pcre.sls

added watch statement to restart postfix

---

README.rst
pillar.example
postfix/map.jinja
postfix/postsrsd.sls

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/saltstack-formulas/postfix-formula/52)

add support for postsrsd

---

postfix/files/main.cf

Following [@aboe76 suggestion](https://github.com/saltstack-formulas/postfix-formula/commit/b0aa531297cd28fe52ebebb1991d42c840b0b2cd#commitcomment-21525749)

Minor formatting change

---

pillar.example
postfix/aliases
postfix/config.sls
postfix/defaults.yaml
postfix/files/main.cf
postfix/files/mapping.j2
postfix/files/master.cf
postfix/init.sls
postfix/map.jinja
postfix/osmap.yaml

Just added the defaults/maps stuff.

Finish #59

---

postfix/files/main.cf
postfix/files/master.cf

As discussed [here](https://github.com/saltstack-formulas/postfix-formula/pull/65#issuecomment-374011761)

Fix xbin_prefix parameter, add managed by Salt headers

---

.kitchen.yml
.travis.yml
Gemfile

Testing is failing in #74.
Add missing Gemfile, updated inspec verifier reporter format

Fix testing

---

.gitignore
.travis.yml
kitchen.yml
test/integration/default/README.md
test/integration/default/inspec.yml

* Automated using `ssf-formula` (v0.1.0-rc.1)

chore: use `semantic-release` cross-formula standard structure

---

postfix/config.sls
postfix/files/main.cf
postfix/files/master.cf

* Similar situation to https://github.com/saltstack-formulas/logrotate-formula/pull/53
- https://freenode.logbot.info/saltstack-formulas/20200507#c3819526-c3819581
- https://freenode.logbot.info/saltstack-formulas/20200508#c3826763-c3826995
* Send template values by `context`
---
No.

fix: make necessary modifications to get working on `salt-ssh`

---

pillar.example
postfix/config.sls
postfix/files/tls_policy

Signed-off-by: Felipe Zipitria <fzipitria@perceptyx.com>
This PR adds `smtp_tls_policy_maps`. See [postfix TLS readme](http://www.postfix.org/TLS_README.html#client_tls_levels)
---
No.

feat(maps): adds tls_policy map for smtp delivery

---

.travis.yml
kitchen.yml

* Automated using https://github.com/myii/ssf-formula/pull/220

ci(kitchen+travis): use latest pre-salted images

---

postfix/files/main.cf

Signed-off-by: Felipe Zipitria <fzipitria@perceptyx.com>
Fixes warning when reloading postfix.
---
No.

fix(main): fix postconf warning when reloading/starting

---

postfix/config.sls

---
No.
Run postmap also for regexp style maps

run postmap also for regexp maps

---

postfix/config.sls
test/integration/default/controls/postfix_maps_type_spec.rb
test/salt/pillar/default.sls

Signed-off-by: Felipe Zipitria <fzipitria@perceptyx.com>
---
Adds `pcre` and `cidr` maps and their tests. Also add tests for `regexp` map type.
No.
Tests are provieded in pillars.

feat(maps): add more map types and tests

---

test/salt/pillar/default.sls

style: linting for `yamllint`

---

postfix/config.sls
postfix/init.sls

salt-lint complains about these
```
[208] File modes should always contain a leading zero
22
/github/workspace/salt/formulas/postfix-formula/postfix/init.sls:46
23
- mode: 644
```
---
No.
This should fix linter errors found by https://github.com/marketplace/actions/salt-lint 
Properly writing and quoting file modes

style: quote modes/numbers

---

postfix/config.sls
postfix/defaults.yaml
postfix/files/main.cf
postfix/init.sls

---
No.
#118, #121
Set default_database_type to the configured or a default value.
This PR [addresses the changes requested](https://github.com/saltstack-formulas/postfix-formula/pull/121#pullrequestreview-639222800) in the PR, and fixes the same issue in other state files where the variable is used.

fix(config): set default_database_type; fixes #118 (supersedes  #121)
