- postfix/files/main.cf
They must not be added as non-standard parameters, they constitute
data for other files.
Fixes #6.
> Special case the 'aliases' and 'virtual' pillar entries

- postfix/init.sls
- postfix/map.jinja
Hi,
I added a map.jinja as it is suggested by the formula best practice guide. This prepares the formula to be distro independent and to support more configurations.
I added the spf package to the packages variable in the map, but form my POV this should now be deprecated and added at will via pillar lookup stuff if needed.
Please merge.
And expect more to come ;-)
Kind regards
-Marc
> added map.jinja support

- pillar.example
- postfix/config.sls
- postfix/files/main.cf
Hi,
I had the need to provide my own master.cf. Since it was not worth the effort for me to template the whole master.cf file, I only added the option to choose if one wants to let the formula manage the master.cf.
Beware that the main.cf parameters are now in the postfix:config namespace. The pillar.example is updated as well, so that should be clear for everyone.
Greetings,
Jeroen
> Add option to let the module (not) manage the master.cf

- postfix/map.jinja
This enables the formula to work in Arch linux
> Add package/service name for Arch Linux

- pillar.example
- postfix/files/main.cf
- postfix/files/master.cf
- postfix/init.sls
- postfix/map.jinja
- postfix/policyd-spf.sls
I found this formula to change too many settings without proper controls so here is my contribution.
aliases can now be customized per distribution as it is a different path in Gentoo.
policyd-spf is now managed via pillar and has an independent sls file for installation. I looked up the name of the  package for all supported distributions though I can only test Gentoo. Also, I removed the optional configuration file passing in master.cf since I think the distribution should be responsible for having the package use the one that the distribution manages by default.
postgrey now enables relevant option in `smtpd_recipient_restrictions` and it can be changed via pillar.
> Misc enhancements

- postfix/files/main.cf
* Some configuration blocks are now only handled if their basic switch is turned on (SASL, TLS, relaying).
* The recipients and relay restrictions default argument building now takes SASL configuration into consideration to avoid producing a bad configuration by default. I think it needs some kind of work to make it more explicit that this needs cyrus-sasl or dovecot configuration.
* Added some parameters for TLS to hopefully make it more secure by default.
> Finer template management

- pillar.example
- postfix/files/main.cf
- postfix/init.sls
- postfix/sender_canonical
- postfix/virtual
The virtual alias handling does not work.  Output is the raw parsed yaml for the 'postfix:virtual' key.  ie:
```
{'info': ['someuser_1@example.com', 'someuser_2@example.com'], 'singlealiasexample': 'someuser_3@example.com'}
```
Add in handling to map it properly and handle lists as well for distribution groups
Example yaml snippet: 
```
virtual:
groupaliasexample: 
- someuser_1@example.com
- someuser_2@example.com
singlealiasexample: 'someuser_3@example.com'
```
Also added in handling for sender_canonical
Example yaml snippet:
```
sender_canonical:
root: 'servers@example.com'
nagios: 'alerts@example.com'
```
> Fix virtual handling - Add sender_canonical handling

- pillar.example
- postfix/files/main.cf
- postfix/init.sls
- postfix/sasl_passwd
This is my first pull request for a salt-formula. It is heavily plagiarized from the sender_canonical handling.
> enable smtp_sasl_password_maps: hash:/etc/postfix/sasl_password

- postfix/init.sls
There is a bug in the init.sls file that specifies 0644 and not 644. I could have quoted the mode instead however I chose 644 to match the other file mode.
Further reading
https://docs.saltstack.com/en/latest/topics/troubleshooting/yaml_idiosyncrasies.html#integers-are-parsed-as-integers
> Fixing file mode bug in init.sls

- postfix/init.sls
As reported in issue #50, formula needs to respect the file type in order to run postmap/newaliases only when appropriate.
Added support for `default_database_type` while at it. The default value is just the one I found to be the most common but this could be customized via `map.jinja` or determined automatically by calling `postconf -d` however I decided to discard that until someone requests it eventually.
Things that could be done to enhance alias database handling is override `map.jinja` `aliases_file` with pillar provided `alias_database` setting and support running `postalias` on `alias_maps` if it makes any difference wrt `postmap`.
> Make postconf/newaliases respect file type

- postfix/files/main.cf
Before this PR, lists ended up generating things like
```
attribute = 
value1,
value2,
...
valueN,
```
(note the last ",")
This PR [reproduces the behaviour of mappings](https://github.com/saltstack-formulas/postfix-formula/blob/master/postfix/files/mapping.j2#L6), rendering now
```
attribute = value1, value2, ..., valueN
```
> Use join() for iterable values in main.cf

- pillar.example
- postfix/aliases
- postfix/init.sls
Using the alias states makes it easier to add/remove single entries rather than having to migrate the entire file into a pillar config.
> Use alias states for managing mail aliases.

- pillar.example
- postfix/aliases
- postfix/config.sls
- postfix/defaults.yaml
- postfix/files/main.cf
- postfix/files/mapping.j2
- postfix/files/master.cf
- postfix/init.sls
- postfix/map.jinja
- postfix/osmap.yaml
- **master.cf: made submission configurable**
- **master.cf: added dovecot**
- **Let the user handle mappings manually**  
In some situations `mappings:` just does not cut it. Therefore, when `mappings:` is absent from pillar, let the user handle those parameters manually.
Based on #62 which is based on #59
> Configurable master_config.cf

- pillar.example
- postfix/aliases
- postfix/config.sls
- postfix/defaults.yaml
- postfix/files/main.cf
- postfix/files/mapping.j2
- postfix/files/master.cf
- postfix/init.sls
- postfix/map.jinja
Hi @EvaSDK, @davidkarlsen, @imran1008,
I had to adjust quite a bit to add support for FreeBSD so the diff
became rather big so I'm pinging you main contributors here.
Would be great if someone can check if those changes won't
break existing setups. The actual changes to managed files
should be rather limited like some options in `main.cf` moving
around because of the for-loop I added in 8eed2547735865.
The FreeBSD jail I've made this changes for isn't in production
yet as I have to add things like spamfilters first but it's happily
sending cron mails already.
Regards, Florian
PS: @aboe76 looks like I can't request reviews from these guys??
> Restructured to Add Support for FreeBSD

- postfix/files/mapping.j2
python3 deprecated iteritems with just items.
> replace iteritems with items

- pillar.example
- postfix/files/virtual_alias_maps.cf
- postfix/files/virtual_mailbox_domains.cf
- postfix/files/virtual_mailbox_maps.cf
Add a mysql query to virtual_mailbox_domains, virtual_alias_maps  virtual_mailbox_maps if mysql is declared in main.cf within these options.
If no pillar is defined, it uses default values.
If no mysql is used, nothing is changed.
> Add a mysql query to 'virtual' files

- README.rst
- pillar.example
- postfix/files/master.cf
- postfix/services.jinja
Currently master.cf only allows for _very_ limited configuration
options mainly focussed on SMTP submission settings.
This is rather limited and does not scale very well for managing
the other services defined in master.cf.
This patch has moved all the service definitions into a jinja file
and generates the master.cf service definition on the fly based on
these defaults.
Defaults can be overridden in a pillar to customize the rendered
master.cf file accordingly to local needs.
Undefined values will be filled with the postfix defaults.
Care has been taken that the previous ways of managing the submission
configuration options are still supported for backwards compatibility
to prevent breakage for existing users of the formula.
> Allow for full managed master.cf services

- .kitchen.yml
- .travis.yml
- test/integration/default/pkgs_spec.rb
- test/integration/default/service_spec.rb
Using it [to check this PR](https://github.com/saltstack-formulas/postfix-formula/pull/65#issuecomment-373957589), I think it can be useful to implement it.
> Basic testing framework

- postfix/files/master.cf
When using i.e. 
```yaml
postfix:
manage_master_config: True
master_config:
enable_submission: False
submission:
smtpd_recipient_restrictions:
- reject_unknown_recipient_domain
- reject_non_fqdn_recipient
- permit_sasl_authenticated
- reject
```
the template uses `", "` (notice the blank) to join the list. This results in
> fatal: unexpected command-line argument: nameofsetting,
This one-character PR fixes the bug.
> master.cf: submission: CSV must not use blank

- pillar.example
- postfix/files/main.cf
Allow to disable ipv6/ipv4
Ref. https://unix.stackexchange.com/questions/64414/ipv6-support-is-disabled-warnings
> add inet_protocols

- postfix/files/main.cf
Fixes the creation of duplicated parameters on main.cf by using the
"set_parameter" macro to append the mapping parameter to the
"processed_parameters" list.
> Fix duplicated mapping parameters on main.cf

- pillar.example
- postfix/init.sls
The postfix service is currently being restarted whenever a
config item changes.
This is unnecessary as the postfix service can reload a new
config.
Set reload: True to prevent unnecessary restarts of the service.
The old behavior can be restored by setting the pillar key
reload_service to False.
> Reload postfix service by default.

- pillar.example
- postfix/files/master.cf
- postfix/services.jinja
As promised in PR #75 , here's a further (and hopefully final)
iteration of the master.cf service handling:
- Bring dovecot and policyd-spf configuration in line with the
extras_services item added in PR #75 
- Remove policyd-spf configuration again from services.jinja,
handle this in master.cf instead, where it was before
- Allow for completely custom services to be added via a pillar
definition in postfix:master_config:services
- Fix legacy dovecot argv example in pillar.example: The example
showed the extra_args being defined as part of the argv
parameter, something that would clash with the actual code and
result in a duplicate '-d ${recipient}' definition in the config.
> Further improvements on extra services configured in master.cf

- pillar.example
Add dovecot example using the services dictionary with a note that
LMTP delivery might be better.
Slight improvements about pillar example settings.
Reorder examples, put the services dictionary examples which allow
more control above the previous dovecot and submission examples.
Add a note about backwards compatibility to indicate that these
options are still supported.
> Improve pillar example

- postfix/files/main.cf
- postfix/init.sls
http://www.postfix.org/DATABASE_README.html#types specifies the lookup
table types postfix understands.
Most are defined as type:/path/to/table which is currently supported
by the postfix formula.
This does break though as soon as the proxy table type is used which is
a prefix to a normal table definition to indicate caching is requested.
This PR changes the code to discard the proxy prefix to ensure that the
usual logic applies again.
> Fix table type for proxy tables

- .kitchen.yml
- pillar.example
- postfix/files/master.cf
Add switch no_args to allow define also internal services without user= and argv=.
It is needed for example for creation from several relay services and using them with randmap.
> Add additinoal internal services

- pillar.example
- postfix/files/main.cf
- postfix/files/mapping.j2
With this change the following becomes feasible:
```yaml
postfix:
config:
virtual_alias_maps: "$my_va_map"
my_va_map: hash:{{ pillar['userland_etc'] }}/postfix/virtual_alias_maps
mapping:
my_va_map:
- '@example.test': catchall@example.test
```
resulting in
```yaml
----------                                                                                                
ID: /usr/local/etc/postfix/main.cf                                                              
Function: file.managed                                                                                
Result: True                                                                                        
Comment: File /usr/local/etc/postfix/main.cf updated                                                 
Started: 20:22:32.857905 …
```
> Fix #89 by ignoring only keys which are actually used in Pillar 'postfix:mapping'

- postfix/init.sls
This also provides an ID to be used in a watch_in statement.
Tested on FreeBSD 11.2 and Debian 10.
> fix(service): restart service on package change

- .travis.yml
- .yamllint
- pillar.example
- postfix/defaults.yaml
- postfix/osfamilymap.yaml
- postfix/services.yaml
- test/integration/default/inspec.yml
* Semi-automated using `ssf-formula` (v0.5.0)
* Fix (or ignore) errors shown below:
```bash
postfix-formula$ $(grep "\- yamllint" .travis.yml | sed -e "s:^\s\+-\s\(.*\):\1:")
./postfix/osfamilymap.yaml
1:1       warning  missing document start "---"  (document-start)
./postfix/services.yaml
11:1      warning  missing document start "---"  (document-start)
12:1      warning  comment not indented like content  (comments-indentation)
221:1     warning  comment not indented like content  (comments-indentation)
./postfix/defaults.yaml
4:1       warning  missing document start "---"  (document-start)
pillar.example
1:1       warning  missing document start "---"  (document-start)
2:25      warning  truthy value should be one of [false, true]  (truthy)
13:17     warning  truthy value should be …
```
> feat(yamllint): include for this repo and apply rules throughout

- .travis.yml
- .yamllint
- pillar.example
* Semi-automated using https://github.com/myii/ssf-formula/pull/27
* Fix errors shown below:
```bash
postfix-formula$ yamllint -s .
./pillar.example
92:15     error    empty value in block mapping  (empty-values)
```
> ci(yamllint): add rule `empty-values` & use new `yaml-files` setting

- postfix/defaults.yaml
- postfix/files/main.cf
- postfix/init.sls
- postfix/osfamilymap.yaml
Signed-off-by: Felipe Zipitria <fzipitria@perceptyx.com>
---
No.
Issue #111 .
Creates file needed by opensuse to prevent system changing config files after salt has created them.
Tests will be merged in #108 after merging this one.
> fix(opensuse): fixes config files generation in opensuse

- postfix/config.sls
- postfix/init.sls
- postfix/iptables-input.sls
- postfix/mysql.sls
- postfix/pcre.sls
- postfix/policyd-spf.sls
- postfix/postgrey.sls
- postfix/postsrsd.sls
---
No, but will break dependencies to this formula resources's IDs being used in other formulas.
Should fix #119
Modified the resources IDs in the state files to follow the pattern proposed in the [template-formula](https://github.com/saltstack-formulas/template-formula/)
> fix(resources): modify names to match template-formula's
